### ISSUE TITLE
Labels css have swapped background and font colors in var names

### ISSUE THREAD

**Issue by stefano-ottolenghi** [neo4j-documentation/docs-ui#241]
For example,

```css
span.label--discontinued {
  background: var(--discontinued-color);
  color: var(--discontinued-background-color);
}
```

var for background lacks `background` in name and viceversa. Applies probably to all except for `deprecated`.
